# Request spec for upstream `state` binding/expiry semantics
# (reqs/auth.md R-ETP6-60VA).
require "rails_helper"

RSpec.describe "OAuth upstream state binding", type: :request do
  include ActiveSupport::Testing::TimeHelpers

  let(:provider) { Rails.configuration.x.google_identity_provider }
  let(:registered_redirect) { "https://client.example.com/cb" }

  around do |example|
    previous_domain = Rails.configuration.x.google_workspace_domain
    Rails.configuration.x.google_workspace_domain = "allowed.example"
    example.run
    Rails.configuration.x.google_workspace_domain = previous_domain
  end

  def register_client
    record, _ = OauthClient.register(
      client_name: "State Binding Client",
      redirect_uris: [ registered_redirect ],
      token_endpoint_auth_method: "none"
    )
    record
  end

  def initiate_authorize(client_record)
    get "https://www.example.com/oauth/authorize",
        params: {
          client_id: client_record.client_id,
          redirect_uri: registered_redirect,
          response_type: "code",
          scope: "openid",
          state: "client-state",
          code_challenge: "abc",
          code_challenge_method: "S256"
        }
    URI.decode_www_form(URI.parse(response.location).query).to_h["state"]
  end

  it "R-ETP6-60VA generates an unguessable upstream state value (high-entropy, distinct per request)" do
    client_record = register_client
    samples = Array.new(5) { initiate_authorize(client_record) }
    expect(samples.uniq.length).to eq(samples.length)
    samples.each { |s| expect(s.to_s.length).to be >= 24 }
  end

  it "R-ETP6-60VA rejects the callback when the returned state was not generated by this service" do
    register_client
    get "https://www.example.com/oauth/google/callback",
        params: { code: "irrelevant", state: "not-a-real-state" },
        headers: { "X-Forwarded-Proto" => "https" }
    expect(response).to have_http_status(:bad_request)
    expect(response.body).to include("Unknown or expired")
  end

  it "R-ETP6-60VA treats upstream state as single-use (replay rejected after consumption)" do
    client_record = register_client
    upstream_state = initiate_authorize(client_record)
    provider.stub_code(
      "code-once",
      sub: "google-sub-replay",
      email: "user@allowed.example",
      hosted_domain: "allowed.example"
    )

    get "https://www.example.com/oauth/google/callback",
        params: { code: "code-once", state: upstream_state },
        headers: { "X-Forwarded-Proto" => "https" }
    expect(response).to have_http_status(:found)

    get "https://www.example.com/oauth/google/callback",
        params: { code: "code-once", state: upstream_state },
        headers: { "X-Forwarded-Proto" => "https" }
    expect(response).to have_http_status(:bad_request)
  end

  it "R-ETP6-60VA rejects callbacks presented from a different browser session" do
    client_record = register_client
    upstream_state = initiate_authorize(client_record)

    # Drop the cookie jar so the next request looks like a fresh
    # browser presenting the captured state.
    reset!

    get "https://www.example.com/oauth/google/callback",
        params: { code: "ignored", state: upstream_state },
        headers: { "X-Forwarded-Proto" => "https" }
    expect(response).to have_http_status(:bad_request)
    expect(response.body).to include("Unknown or expired")
  end

  it "R-ETP6-60VA rejects callbacks whose state has expired" do
    client_record = register_client
    upstream_state = initiate_authorize(client_record)

    # Advance past the recorded expires_at without consuming the entry.
    travel_to(Time.now.utc + 1.hour) do
      get "https://www.example.com/oauth/google/callback",
          params: { code: "ignored", state: upstream_state },
          headers: { "X-Forwarded-Proto" => "https" }
    end
    expect(response).to have_http_status(:bad_request)
    expect(response.body).to include("Unknown or expired")
  end
end
